export const SET_ORDERS: 'SET_ORDERS' = 'SET_ORDERS';
export const GET_ORDER_REQUEST: 'GET_ORDER_REQUEST' = 'GET_ORDER_REQUEST';
export const GET_ORDER_SUCCESS: 'GET_ORDER_SUCCESS' = 'GET_ORDER_SUCCESS';
export const GET_ORDER_ERROR: 'GET_ORDER_ERROR' = 'GET_ORDER_ERROR';
export const DELETE_ORDERS: 'DELETE_ORDERS' = 'DELETE_ORDERS';