export const CREATE_ORDER_REQUEST: 'CREATE_ORDER_REQUEST' = 'CREATE_ORDER_REQUEST';
export const CREATE_ORDER_SUCCESS: 'CREATE_ORDER_SUCCESS' = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_ERROR: 'CREATE_ORDER_ERROR' = 'CREATE_ORDER_ERROR';

export const DELETE_INGREDIENT: 'DELETE_INGREDIENT' = 'DELETE_INGREDIENT';
export const DELETE_ORDER: 'DELETE_ORDER' = 'DELETE_ORDER';
export const ADD_INGREDIENT: 'ADD_INGREDIENT' = 'ADD_INGREDIENT';
export const REPLACE_BUN: 'REPLACE_BUN' = 'REPLACE_BUN';
export const REORDER: 'REORDER' = 'REORDER';
export const DEFAULT: 'DEFAULT' = 'DEFAULT';